## Importing Numpy

In [ ]:
import numpy as np

## Creating an array of 10 Zeros

In [6]:
a0 = np.zeros((1,10))
a0

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Creating an arrray of 10 one's

In [7]:
a1 = np.ones((1,10))
a1

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## Creating an array of 10 fives

In [12]:
a5 = np.ones(10)*5
a5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## Creating an array of the integers from 10 to 50

In [14]:
ar = np.arange(10,51)
ar

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

## Creating a 3x3 matrix with values ranging from 0 to 8

In [16]:
am = np.arange(0,9).reshape(3,3)
am

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Creating a 3x3 Identity matrix

In [17]:
ai = np.eye(3)
ai

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Using Numpy to generate random between 0 and 1

In [20]:
rand = np.random.normal(0,1,1)
rand

array([0.37980313])

## Using Numpy to generate an array of 25 random numbers from aa standard normal distribution

In [21]:
rand_25 = np.random.normal(0,1,25)
rand_25

array([ 0.01660935, -0.63544901,  1.18668379, -0.44277904,  0.46910579,
       -0.81065743, -0.42042314,  0.9127911 ,  2.97258721, -2.465852  ,
        0.32144418, -0.36502808, -0.82799483,  1.4075261 , -0.35972994,
       -0.25090695, -0.42940719,  3.62526118,  1.367598  ,  0.59331745,
       -0.02302892,  0.86666882,  0.92796749,  1.03107116,  0.61341089])

## Creating matrix with the following array

In [30]:
atx = np.arange(0.01,1.01,0.01).reshape(10,10)
atx

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

## Creating an array of 20 linearlyspaced points between 0 and 1

In [24]:
al = np.linspace(0,1,20)
al

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Writing code that produces the output

In [38]:
mat = np.arange(1,26).reshape(5,5)
mat
matt = mat[:3,:4]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [43]:
mat = np.arange(1,26).reshape(5,5)
mat
matt = mat[2:5, 1:5]
matt

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

## Code that reproduces the output below

In [47]:
aw = mat[3][-1]
aw

20

## Code that produces the output below

In [68]:
aww = mat[:3,1:2]
aww

array([[ 2],
       [ 7],
       [12]])

## Code that produces the output below

In [70]:
ak = mat[-1]
ak

array([21, 22, 23, 24, 25])

## Code that produces the output below

In [72]:
an = mat[-2:]
an

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

## Sum of all Numbers in Mat

## The standard deviation of the values in mat

## To get the sum of all columns in mat

In [76]:
aw = mat.sum(axis=0)
aw

array([55, 60, 65, 70, 75])